data_cfg:
  dataset_name: CASIA-B
  dataset_root: ./CASIA-B-pkl
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 60000
  save_name: GaitPart
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  eval_func: identification

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
    log_accuracy: true
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: GaitPart
  backbone_cfg:
    in_channels: 1
    layers_cfg:
      - BC-32
      - BC-32
      - M
      - FC-64-2
      - FC-64-2
      - M
      - FC-128-3
      - FC-128-3
    type: Plain
  SeparateFCs:
    in_channels: 128
    out_channels: 128
    parts_num: 16
  bin_num:
    - 16


optimizer_cfg:
  lr: 0.0001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 50000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitPart
  sync_BN: false
  total_iter: 60000
  sampler:
    batch_shuffle: false
    batch_size:
      - 4
      - 8
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    frames_skip_num: 10
    sample_type: fixed_ordered
    type: TripletSampler
